# SPDX-FileCopyrightText: 2024 Pablo Portas L贸pez <pablo.portas@udc.es>
#
# SPDX-License-Identifier: GPL-3.0-only

name: " Informe de error/bug"
description: "Crea un informe para ayudarnos a mejorar"
title: " <bug>"
labels: ["bug", "good first issue"]
assignees: 
  - TeenBiscuits
body:
  - type: markdown
    attributes:
      value: |
        隆Gracias por colaborar cazando esos bugs que tantos dolores de cabeza dan! 
  - type: input
    id: bug
    attributes:
      label: "El error/bug"
      description: "Una descripci贸n clara y concisa de cu谩l es el error"
    validations:
      required: true
  - type: dropdown
    id: ubi
    attributes:
      label: 驴Donde se encuentra el error/bug?
      multiple: true
      options:
        - Web / Documentaci贸n
        - C贸digo
        - GitHub (Actions...)
        - Otro
  - type: input
    id: steps
    attributes:
      label: "Pasos a reproducir"
      description: "驴Que hay que hacer para que el error/bug pase?"
      placeholder: "1. Hago esto/aquello..."
    validations:
      required: false
  - type: input
    id: extra
    attributes:
      label: "Informaci贸n extra"
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Salida/Logs relevantes"
      description: Copie y pegue cualquier registro relevante. Esto se formatear谩 autom谩ticamente en c贸digo, por lo que no ser谩 necesario utilizar comillas invertidas.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: "C贸digo de Conducta"
      description: Al enviar este bug, acepta seguir nuestro [C贸digo de Conducta](https://github.com/TeenBiscuits/Pro2324#coc-ov-file)
      options:
        - label: Acepto seguir el C贸digo de conducta de este proyecto.
          required: true