# SPDX-FileCopyrightText: 2024 Pablo Portas L칩pez <pablo.portas@udc.es>
#
# SPDX-License-Identifier: GPL-3.0-only

name: "游냍 Informe de error/bug"
description: "Crea un informe para ayudarnos a mejorar"
title: "[BUG] <bug>"
labels: ["bug", "good first issue"]
assignees: "TeenBiscuits"
body:
- type: input
  id: bug
  attributes:
    label: "El error/bug"
    description: "Una descripci칩n clara y concisa de cu치l es el error"
  validations:
    required: true
- type: input
  id: steps
  attributes:
    label: "Pasos para reproducir el comportamiento"
    description: "쯈ue hay que hacer para que el error/bug pase?"
    placeholder: "1. Hago esto/aquello..."
  validations:
    required: false
- type: input
  id: extra
  attributes:
    label: 'Informaci칩n extra'
  validations:
    required: false
