# SPDX-FileCopyrightText: 2024 Pablo Portas L贸pez <pablo.portas@udc.es>
#
# SPDX-License-Identifier: GPL-3.0-only

name: " Solicitud de funci贸n"
description: "Sugiere una idea para este proyecto."
title: ' <mejora>'
labels: 'mejora'
assignees: 'TeenBiscuits'
body:
  - type: markdown
    attributes:
      value: |
        隆Gracias por colaborar con tus ideas! 
  - type: input
    id: title
    attributes:
      label: "La idea "
      description: "Descripci贸n breve de la idea que tienes para este proyecto"
    validations:
      required: true
  - type: dropdown
    id: ubi
    attributes:
      label: 驴Para donde es la mejora?
      multiple: true
      options:
        - Web / Documentaci贸n
        - C贸digo
        - GitHub (Actions...)
        - Otro
  - type: input
    id: steps
    attributes:
      label: "Cu茅ntame m谩s "
      description: "Explica tu idea"
      placeholder: "Explica en profundidad tu idea..."
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: C贸digo de Conducta
      description: Al enviar este bug, acepta seguir nuestro [C贸digo de Conducta](https://github.com/TeenBiscuits/Pro2324#coc-ov-file)
      options:
        - label: Acepto seguir el C贸digo de conducta de este proyecto.
          required: true
