# SPDX-FileCopyrightText: 2024 Pablo Portas López <pablo.portas@udc.es>
#
# SPDX-License-Identifier: GPL-3.0-only

name: "💡 Solicitud de función"
description: "Sugiere una idea para este proyecto."
title: '[SOLICITUD DE FUNCIÓN] <mejora>'
labels: 'mejora'
assignees: 'TeenBiscuits'
body:
  - type: input
    id: title
    attributes:
      label: "La idea"
      description: "Descripción breve de la idea que tienes para este proyecto"
    validations:
      required: true
  - type: input
    id: steps
    attributes:
      label: "Cuéntame más"
      description: "Explica tu idea"
      placeholder: "Explica en profundidad tu idea..."
    validations:
      required: false
